### ISSUE TITLE
Adding new product doesn't show in elasticsearch result

### ISSUE THREAD

**Issue by fruqi** [javereec/spree_elasticsearch#10]
Hi there,

I'm wondering why every time I add a new product, I can't see the product I just added in the elasticsearch results.
Except, if I call import command from the terminal and search again then the new product is there.

Just out of curiosity, is this something that I need to do by myself or did I miss something.

Thanks in advance.

**Comment by javereec** [comment]
You've probably not implemented a callback. I've updated the documentation to clarify this. I don't do it in the plugin because there are multiple possibilities.

Check the updated README and https://github.com/elasticsearch/elasticsearch-rails/tree/master/elasticsearch-model#updating-the-documents-in-the-index

**Comment by fruqi** [comment]
Thanks for the updated document.
But the thing is that I tried that before and it didn't update the index.
FYI, I have used elasticsearch before and using callback indeed adding record(s) to the index but not this time. I'm still not sure what's causing that up until now.
Anyway, I used sidekiq to do the callback and it works.

Thanks for your time, cheers.
